/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as SidebarRouteRouteImport } from './routes/_sidebar/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SidebarWorkoutSheetsRouteImport } from './routes/_sidebar/workout-sheets'
import { Route as SidebarStudentsRouteImport } from './routes/_sidebar/students'
import { Route as SidebarPlansRouteImport } from './routes/_sidebar/plans'
import { Route as SidebarPaymentsRouteImport } from './routes/_sidebar/payments'
import { Route as SidebarInstructorsRouteImport } from './routes/_sidebar/instructors'
import { Route as SidebarExercisesRouteImport } from './routes/_sidebar/exercises'
import { Route as SidebarEnrollmentsRouteImport } from './routes/_sidebar/enrollments'
import { Route as SidebarDashboardRouteImport } from './routes/_sidebar/dashboard'
import { Route as SidebarAuditLogsRouteImport } from './routes/_sidebar/audit-logs'
import { Route as SidebarAdminUsersRouteImport } from './routes/_sidebar/admin-users'
import { Route as SidebarWorkoutSheetsIndexRouteImport } from './routes/_sidebar/workout-sheets/index'
import { Route as SidebarStudentsIndexRouteImport } from './routes/_sidebar/students/index'
import { Route as SidebarPlansIndexRouteImport } from './routes/_sidebar/plans/index'
import { Route as SidebarPaymentsIndexRouteImport } from './routes/_sidebar/payments/index'
import { Route as SidebarInstructorsIndexRouteImport } from './routes/_sidebar/instructors/index'
import { Route as SidebarExercisesIndexRouteImport } from './routes/_sidebar/exercises/index'
import { Route as SidebarEnrollmentsIndexRouteImport } from './routes/_sidebar/enrollments/index'
import { Route as SidebarAuditLogsIndexRouteImport } from './routes/_sidebar/audit-logs/index'
import { Route as SidebarAdminUsersIndexRouteImport } from './routes/_sidebar/admin-users/index'
import { Route as SidebarWorkoutSheetsCreateRouteImport } from './routes/_sidebar/workout-sheets/create'
import { Route as SidebarWorkoutSheetsWorkoutSheetIdRouteImport } from './routes/_sidebar/workout-sheets/$workoutSheetId'
import { Route as SidebarStudentsCreateRouteImport } from './routes/_sidebar/students/create'
import { Route as SidebarStudentsStudentIdRouteImport } from './routes/_sidebar/students/$studentId'
import { Route as SidebarPlansCreateRouteImport } from './routes/_sidebar/plans/create'
import { Route as SidebarPlansPlanIdRouteImport } from './routes/_sidebar/plans/$planId'
import { Route as SidebarInstructorsCreateRouteImport } from './routes/_sidebar/instructors/create'
import { Route as SidebarInstructorsInstructorIdRouteImport } from './routes/_sidebar/instructors/$instructorId'
import { Route as SidebarExercisesCreateRouteImport } from './routes/_sidebar/exercises/create'
import { Route as SidebarExercisesExerciseIdRouteImport } from './routes/_sidebar/exercises/$exerciseId'
import { Route as SidebarEnrollmentsCreateRouteImport } from './routes/_sidebar/enrollments/create'
import { Route as SidebarEnrollmentsEnrollmentIdRouteImport } from './routes/_sidebar/enrollments/$enrollmentId'
import { Route as SidebarAdminUsersCreateRouteImport } from './routes/_sidebar/admin-users/create'
import { Route as SidebarAdminUsersUserIdRouteImport } from './routes/_sidebar/admin-users/$userId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarWorkoutSheetsRoute = SidebarWorkoutSheetsRouteImport.update({
  id: '/workout-sheets',
  path: '/workout-sheets',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarStudentsRoute = SidebarStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarPlansRoute = SidebarPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarPaymentsRoute = SidebarPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarInstructorsRoute = SidebarInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarExercisesRoute = SidebarExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarEnrollmentsRoute = SidebarEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDashboardRoute = SidebarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAuditLogsRoute = SidebarAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAdminUsersRoute = SidebarAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarWorkoutSheetsIndexRoute =
  SidebarWorkoutSheetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarWorkoutSheetsRoute,
  } as any)
const SidebarStudentsIndexRoute = SidebarStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarStudentsRoute,
} as any)
const SidebarPlansIndexRoute = SidebarPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarPlansRoute,
} as any)
const SidebarPaymentsIndexRoute = SidebarPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarPaymentsRoute,
} as any)
const SidebarInstructorsIndexRoute = SidebarInstructorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarInstructorsRoute,
} as any)
const SidebarExercisesIndexRoute = SidebarExercisesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarExercisesRoute,
} as any)
const SidebarEnrollmentsIndexRoute = SidebarEnrollmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarEnrollmentsRoute,
} as any)
const SidebarAuditLogsIndexRoute = SidebarAuditLogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarAuditLogsRoute,
} as any)
const SidebarAdminUsersIndexRoute = SidebarAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarAdminUsersRoute,
} as any)
const SidebarWorkoutSheetsCreateRoute =
  SidebarWorkoutSheetsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => SidebarWorkoutSheetsRoute,
  } as any)
const SidebarWorkoutSheetsWorkoutSheetIdRoute =
  SidebarWorkoutSheetsWorkoutSheetIdRouteImport.update({
    id: '/$workoutSheetId',
    path: '/$workoutSheetId',
    getParentRoute: () => SidebarWorkoutSheetsRoute,
  } as any)
const SidebarStudentsCreateRoute = SidebarStudentsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SidebarStudentsRoute,
} as any)
const SidebarStudentsStudentIdRoute =
  SidebarStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => SidebarStudentsRoute,
  } as any)
const SidebarPlansCreateRoute = SidebarPlansCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SidebarPlansRoute,
} as any)
const SidebarPlansPlanIdRoute = SidebarPlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => SidebarPlansRoute,
} as any)
const SidebarInstructorsCreateRoute =
  SidebarInstructorsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => SidebarInstructorsRoute,
  } as any)
const SidebarInstructorsInstructorIdRoute =
  SidebarInstructorsInstructorIdRouteImport.update({
    id: '/$instructorId',
    path: '/$instructorId',
    getParentRoute: () => SidebarInstructorsRoute,
  } as any)
const SidebarExercisesCreateRoute = SidebarExercisesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SidebarExercisesRoute,
} as any)
const SidebarExercisesExerciseIdRoute =
  SidebarExercisesExerciseIdRouteImport.update({
    id: '/$exerciseId',
    path: '/$exerciseId',
    getParentRoute: () => SidebarExercisesRoute,
  } as any)
const SidebarEnrollmentsCreateRoute =
  SidebarEnrollmentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => SidebarEnrollmentsRoute,
  } as any)
const SidebarEnrollmentsEnrollmentIdRoute =
  SidebarEnrollmentsEnrollmentIdRouteImport.update({
    id: '/$enrollmentId',
    path: '/$enrollmentId',
    getParentRoute: () => SidebarEnrollmentsRoute,
  } as any)
const SidebarAdminUsersCreateRoute = SidebarAdminUsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SidebarAdminUsersRoute,
} as any)
const SidebarAdminUsersUserIdRoute = SidebarAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => SidebarAdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin-users': typeof SidebarAdminUsersRouteWithChildren
  '/audit-logs': typeof SidebarAuditLogsRouteWithChildren
  '/dashboard': typeof SidebarDashboardRoute
  '/enrollments': typeof SidebarEnrollmentsRouteWithChildren
  '/exercises': typeof SidebarExercisesRouteWithChildren
  '/instructors': typeof SidebarInstructorsRouteWithChildren
  '/payments': typeof SidebarPaymentsRouteWithChildren
  '/plans': typeof SidebarPlansRouteWithChildren
  '/students': typeof SidebarStudentsRouteWithChildren
  '/workout-sheets': typeof SidebarWorkoutSheetsRouteWithChildren
  '/admin-users/$userId': typeof SidebarAdminUsersUserIdRoute
  '/admin-users/create': typeof SidebarAdminUsersCreateRoute
  '/enrollments/$enrollmentId': typeof SidebarEnrollmentsEnrollmentIdRoute
  '/enrollments/create': typeof SidebarEnrollmentsCreateRoute
  '/exercises/$exerciseId': typeof SidebarExercisesExerciseIdRoute
  '/exercises/create': typeof SidebarExercisesCreateRoute
  '/instructors/$instructorId': typeof SidebarInstructorsInstructorIdRoute
  '/instructors/create': typeof SidebarInstructorsCreateRoute
  '/plans/$planId': typeof SidebarPlansPlanIdRoute
  '/plans/create': typeof SidebarPlansCreateRoute
  '/students/$studentId': typeof SidebarStudentsStudentIdRoute
  '/students/create': typeof SidebarStudentsCreateRoute
  '/workout-sheets/$workoutSheetId': typeof SidebarWorkoutSheetsWorkoutSheetIdRoute
  '/workout-sheets/create': typeof SidebarWorkoutSheetsCreateRoute
  '/admin-users/': typeof SidebarAdminUsersIndexRoute
  '/audit-logs/': typeof SidebarAuditLogsIndexRoute
  '/enrollments/': typeof SidebarEnrollmentsIndexRoute
  '/exercises/': typeof SidebarExercisesIndexRoute
  '/instructors/': typeof SidebarInstructorsIndexRoute
  '/payments/': typeof SidebarPaymentsIndexRoute
  '/plans/': typeof SidebarPlansIndexRoute
  '/students/': typeof SidebarStudentsIndexRoute
  '/workout-sheets/': typeof SidebarWorkoutSheetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/admin-users/$userId': typeof SidebarAdminUsersUserIdRoute
  '/admin-users/create': typeof SidebarAdminUsersCreateRoute
  '/enrollments/$enrollmentId': typeof SidebarEnrollmentsEnrollmentIdRoute
  '/enrollments/create': typeof SidebarEnrollmentsCreateRoute
  '/exercises/$exerciseId': typeof SidebarExercisesExerciseIdRoute
  '/exercises/create': typeof SidebarExercisesCreateRoute
  '/instructors/$instructorId': typeof SidebarInstructorsInstructorIdRoute
  '/instructors/create': typeof SidebarInstructorsCreateRoute
  '/plans/$planId': typeof SidebarPlansPlanIdRoute
  '/plans/create': typeof SidebarPlansCreateRoute
  '/students/$studentId': typeof SidebarStudentsStudentIdRoute
  '/students/create': typeof SidebarStudentsCreateRoute
  '/workout-sheets/$workoutSheetId': typeof SidebarWorkoutSheetsWorkoutSheetIdRoute
  '/workout-sheets/create': typeof SidebarWorkoutSheetsCreateRoute
  '/admin-users': typeof SidebarAdminUsersIndexRoute
  '/audit-logs': typeof SidebarAuditLogsIndexRoute
  '/enrollments': typeof SidebarEnrollmentsIndexRoute
  '/exercises': typeof SidebarExercisesIndexRoute
  '/instructors': typeof SidebarInstructorsIndexRoute
  '/payments': typeof SidebarPaymentsIndexRoute
  '/plans': typeof SidebarPlansIndexRoute
  '/students': typeof SidebarStudentsIndexRoute
  '/workout-sheets': typeof SidebarWorkoutSheetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/check-in': typeof CheckInRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_sidebar/admin-users': typeof SidebarAdminUsersRouteWithChildren
  '/_sidebar/audit-logs': typeof SidebarAuditLogsRouteWithChildren
  '/_sidebar/dashboard': typeof SidebarDashboardRoute
  '/_sidebar/enrollments': typeof SidebarEnrollmentsRouteWithChildren
  '/_sidebar/exercises': typeof SidebarExercisesRouteWithChildren
  '/_sidebar/instructors': typeof SidebarInstructorsRouteWithChildren
  '/_sidebar/payments': typeof SidebarPaymentsRouteWithChildren
  '/_sidebar/plans': typeof SidebarPlansRouteWithChildren
  '/_sidebar/students': typeof SidebarStudentsRouteWithChildren
  '/_sidebar/workout-sheets': typeof SidebarWorkoutSheetsRouteWithChildren
  '/_sidebar/admin-users/$userId': typeof SidebarAdminUsersUserIdRoute
  '/_sidebar/admin-users/create': typeof SidebarAdminUsersCreateRoute
  '/_sidebar/enrollments/$enrollmentId': typeof SidebarEnrollmentsEnrollmentIdRoute
  '/_sidebar/enrollments/create': typeof SidebarEnrollmentsCreateRoute
  '/_sidebar/exercises/$exerciseId': typeof SidebarExercisesExerciseIdRoute
  '/_sidebar/exercises/create': typeof SidebarExercisesCreateRoute
  '/_sidebar/instructors/$instructorId': typeof SidebarInstructorsInstructorIdRoute
  '/_sidebar/instructors/create': typeof SidebarInstructorsCreateRoute
  '/_sidebar/plans/$planId': typeof SidebarPlansPlanIdRoute
  '/_sidebar/plans/create': typeof SidebarPlansCreateRoute
  '/_sidebar/students/$studentId': typeof SidebarStudentsStudentIdRoute
  '/_sidebar/students/create': typeof SidebarStudentsCreateRoute
  '/_sidebar/workout-sheets/$workoutSheetId': typeof SidebarWorkoutSheetsWorkoutSheetIdRoute
  '/_sidebar/workout-sheets/create': typeof SidebarWorkoutSheetsCreateRoute
  '/_sidebar/admin-users/': typeof SidebarAdminUsersIndexRoute
  '/_sidebar/audit-logs/': typeof SidebarAuditLogsIndexRoute
  '/_sidebar/enrollments/': typeof SidebarEnrollmentsIndexRoute
  '/_sidebar/exercises/': typeof SidebarExercisesIndexRoute
  '/_sidebar/instructors/': typeof SidebarInstructorsIndexRoute
  '/_sidebar/payments/': typeof SidebarPaymentsIndexRoute
  '/_sidebar/plans/': typeof SidebarPlansIndexRoute
  '/_sidebar/students/': typeof SidebarStudentsIndexRoute
  '/_sidebar/workout-sheets/': typeof SidebarWorkoutSheetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/student'
    | '/unauthorized'
    | '/admin-users'
    | '/audit-logs'
    | '/dashboard'
    | '/enrollments'
    | '/exercises'
    | '/instructors'
    | '/payments'
    | '/plans'
    | '/students'
    | '/workout-sheets'
    | '/admin-users/$userId'
    | '/admin-users/create'
    | '/enrollments/$enrollmentId'
    | '/enrollments/create'
    | '/exercises/$exerciseId'
    | '/exercises/create'
    | '/instructors/$instructorId'
    | '/instructors/create'
    | '/plans/$planId'
    | '/plans/create'
    | '/students/$studentId'
    | '/students/create'
    | '/workout-sheets/$workoutSheetId'
    | '/workout-sheets/create'
    | '/admin-users/'
    | '/audit-logs/'
    | '/enrollments/'
    | '/exercises/'
    | '/instructors/'
    | '/payments/'
    | '/plans/'
    | '/students/'
    | '/workout-sheets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/student'
    | '/unauthorized'
    | '/dashboard'
    | '/admin-users/$userId'
    | '/admin-users/create'
    | '/enrollments/$enrollmentId'
    | '/enrollments/create'
    | '/exercises/$exerciseId'
    | '/exercises/create'
    | '/instructors/$instructorId'
    | '/instructors/create'
    | '/plans/$planId'
    | '/plans/create'
    | '/students/$studentId'
    | '/students/create'
    | '/workout-sheets/$workoutSheetId'
    | '/workout-sheets/create'
    | '/admin-users'
    | '/audit-logs'
    | '/enrollments'
    | '/exercises'
    | '/instructors'
    | '/payments'
    | '/plans'
    | '/students'
    | '/workout-sheets'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/check-in'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/student'
    | '/unauthorized'
    | '/_sidebar/admin-users'
    | '/_sidebar/audit-logs'
    | '/_sidebar/dashboard'
    | '/_sidebar/enrollments'
    | '/_sidebar/exercises'
    | '/_sidebar/instructors'
    | '/_sidebar/payments'
    | '/_sidebar/plans'
    | '/_sidebar/students'
    | '/_sidebar/workout-sheets'
    | '/_sidebar/admin-users/$userId'
    | '/_sidebar/admin-users/create'
    | '/_sidebar/enrollments/$enrollmentId'
    | '/_sidebar/enrollments/create'
    | '/_sidebar/exercises/$exerciseId'
    | '/_sidebar/exercises/create'
    | '/_sidebar/instructors/$instructorId'
    | '/_sidebar/instructors/create'
    | '/_sidebar/plans/$planId'
    | '/_sidebar/plans/create'
    | '/_sidebar/students/$studentId'
    | '/_sidebar/students/create'
    | '/_sidebar/workout-sheets/$workoutSheetId'
    | '/_sidebar/workout-sheets/create'
    | '/_sidebar/admin-users/'
    | '/_sidebar/audit-logs/'
    | '/_sidebar/enrollments/'
    | '/_sidebar/exercises/'
    | '/_sidebar/instructors/'
    | '/_sidebar/payments/'
    | '/_sidebar/plans/'
    | '/_sidebar/students/'
    | '/_sidebar/workout-sheets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
  CheckInRoute: typeof CheckInRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/workout-sheets': {
      id: '/_sidebar/workout-sheets'
      path: '/workout-sheets'
      fullPath: '/workout-sheets'
      preLoaderRoute: typeof SidebarWorkoutSheetsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/students': {
      id: '/_sidebar/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof SidebarStudentsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/plans': {
      id: '/_sidebar/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof SidebarPlansRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/payments': {
      id: '/_sidebar/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof SidebarPaymentsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/instructors': {
      id: '/_sidebar/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof SidebarInstructorsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/exercises': {
      id: '/_sidebar/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof SidebarExercisesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/enrollments': {
      id: '/_sidebar/enrollments'
      path: '/enrollments'
      fullPath: '/enrollments'
      preLoaderRoute: typeof SidebarEnrollmentsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dashboard': {
      id: '/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SidebarDashboardRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/audit-logs': {
      id: '/_sidebar/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof SidebarAuditLogsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/admin-users': {
      id: '/_sidebar/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof SidebarAdminUsersRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/workout-sheets/': {
      id: '/_sidebar/workout-sheets/'
      path: '/'
      fullPath: '/workout-sheets/'
      preLoaderRoute: typeof SidebarWorkoutSheetsIndexRouteImport
      parentRoute: typeof SidebarWorkoutSheetsRoute
    }
    '/_sidebar/students/': {
      id: '/_sidebar/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof SidebarStudentsIndexRouteImport
      parentRoute: typeof SidebarStudentsRoute
    }
    '/_sidebar/plans/': {
      id: '/_sidebar/plans/'
      path: '/'
      fullPath: '/plans/'
      preLoaderRoute: typeof SidebarPlansIndexRouteImport
      parentRoute: typeof SidebarPlansRoute
    }
    '/_sidebar/payments/': {
      id: '/_sidebar/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof SidebarPaymentsIndexRouteImport
      parentRoute: typeof SidebarPaymentsRoute
    }
    '/_sidebar/instructors/': {
      id: '/_sidebar/instructors/'
      path: '/'
      fullPath: '/instructors/'
      preLoaderRoute: typeof SidebarInstructorsIndexRouteImport
      parentRoute: typeof SidebarInstructorsRoute
    }
    '/_sidebar/exercises/': {
      id: '/_sidebar/exercises/'
      path: '/'
      fullPath: '/exercises/'
      preLoaderRoute: typeof SidebarExercisesIndexRouteImport
      parentRoute: typeof SidebarExercisesRoute
    }
    '/_sidebar/enrollments/': {
      id: '/_sidebar/enrollments/'
      path: '/'
      fullPath: '/enrollments/'
      preLoaderRoute: typeof SidebarEnrollmentsIndexRouteImport
      parentRoute: typeof SidebarEnrollmentsRoute
    }
    '/_sidebar/audit-logs/': {
      id: '/_sidebar/audit-logs/'
      path: '/'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof SidebarAuditLogsIndexRouteImport
      parentRoute: typeof SidebarAuditLogsRoute
    }
    '/_sidebar/admin-users/': {
      id: '/_sidebar/admin-users/'
      path: '/'
      fullPath: '/admin-users/'
      preLoaderRoute: typeof SidebarAdminUsersIndexRouteImport
      parentRoute: typeof SidebarAdminUsersRoute
    }
    '/_sidebar/workout-sheets/create': {
      id: '/_sidebar/workout-sheets/create'
      path: '/create'
      fullPath: '/workout-sheets/create'
      preLoaderRoute: typeof SidebarWorkoutSheetsCreateRouteImport
      parentRoute: typeof SidebarWorkoutSheetsRoute
    }
    '/_sidebar/workout-sheets/$workoutSheetId': {
      id: '/_sidebar/workout-sheets/$workoutSheetId'
      path: '/$workoutSheetId'
      fullPath: '/workout-sheets/$workoutSheetId'
      preLoaderRoute: typeof SidebarWorkoutSheetsWorkoutSheetIdRouteImport
      parentRoute: typeof SidebarWorkoutSheetsRoute
    }
    '/_sidebar/students/create': {
      id: '/_sidebar/students/create'
      path: '/create'
      fullPath: '/students/create'
      preLoaderRoute: typeof SidebarStudentsCreateRouteImport
      parentRoute: typeof SidebarStudentsRoute
    }
    '/_sidebar/students/$studentId': {
      id: '/_sidebar/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof SidebarStudentsStudentIdRouteImport
      parentRoute: typeof SidebarStudentsRoute
    }
    '/_sidebar/plans/create': {
      id: '/_sidebar/plans/create'
      path: '/create'
      fullPath: '/plans/create'
      preLoaderRoute: typeof SidebarPlansCreateRouteImport
      parentRoute: typeof SidebarPlansRoute
    }
    '/_sidebar/plans/$planId': {
      id: '/_sidebar/plans/$planId'
      path: '/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof SidebarPlansPlanIdRouteImport
      parentRoute: typeof SidebarPlansRoute
    }
    '/_sidebar/instructors/create': {
      id: '/_sidebar/instructors/create'
      path: '/create'
      fullPath: '/instructors/create'
      preLoaderRoute: typeof SidebarInstructorsCreateRouteImport
      parentRoute: typeof SidebarInstructorsRoute
    }
    '/_sidebar/instructors/$instructorId': {
      id: '/_sidebar/instructors/$instructorId'
      path: '/$instructorId'
      fullPath: '/instructors/$instructorId'
      preLoaderRoute: typeof SidebarInstructorsInstructorIdRouteImport
      parentRoute: typeof SidebarInstructorsRoute
    }
    '/_sidebar/exercises/create': {
      id: '/_sidebar/exercises/create'
      path: '/create'
      fullPath: '/exercises/create'
      preLoaderRoute: typeof SidebarExercisesCreateRouteImport
      parentRoute: typeof SidebarExercisesRoute
    }
    '/_sidebar/exercises/$exerciseId': {
      id: '/_sidebar/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof SidebarExercisesExerciseIdRouteImport
      parentRoute: typeof SidebarExercisesRoute
    }
    '/_sidebar/enrollments/create': {
      id: '/_sidebar/enrollments/create'
      path: '/create'
      fullPath: '/enrollments/create'
      preLoaderRoute: typeof SidebarEnrollmentsCreateRouteImport
      parentRoute: typeof SidebarEnrollmentsRoute
    }
    '/_sidebar/enrollments/$enrollmentId': {
      id: '/_sidebar/enrollments/$enrollmentId'
      path: '/$enrollmentId'
      fullPath: '/enrollments/$enrollmentId'
      preLoaderRoute: typeof SidebarEnrollmentsEnrollmentIdRouteImport
      parentRoute: typeof SidebarEnrollmentsRoute
    }
    '/_sidebar/admin-users/create': {
      id: '/_sidebar/admin-users/create'
      path: '/create'
      fullPath: '/admin-users/create'
      preLoaderRoute: typeof SidebarAdminUsersCreateRouteImport
      parentRoute: typeof SidebarAdminUsersRoute
    }
    '/_sidebar/admin-users/$userId': {
      id: '/_sidebar/admin-users/$userId'
      path: '/$userId'
      fullPath: '/admin-users/$userId'
      preLoaderRoute: typeof SidebarAdminUsersUserIdRouteImport
      parentRoute: typeof SidebarAdminUsersRoute
    }
  }
}

interface SidebarAdminUsersRouteChildren {
  SidebarAdminUsersUserIdRoute: typeof SidebarAdminUsersUserIdRoute
  SidebarAdminUsersCreateRoute: typeof SidebarAdminUsersCreateRoute
  SidebarAdminUsersIndexRoute: typeof SidebarAdminUsersIndexRoute
}

const SidebarAdminUsersRouteChildren: SidebarAdminUsersRouteChildren = {
  SidebarAdminUsersUserIdRoute: SidebarAdminUsersUserIdRoute,
  SidebarAdminUsersCreateRoute: SidebarAdminUsersCreateRoute,
  SidebarAdminUsersIndexRoute: SidebarAdminUsersIndexRoute,
}

const SidebarAdminUsersRouteWithChildren =
  SidebarAdminUsersRoute._addFileChildren(SidebarAdminUsersRouteChildren)

interface SidebarAuditLogsRouteChildren {
  SidebarAuditLogsIndexRoute: typeof SidebarAuditLogsIndexRoute
}

const SidebarAuditLogsRouteChildren: SidebarAuditLogsRouteChildren = {
  SidebarAuditLogsIndexRoute: SidebarAuditLogsIndexRoute,
}

const SidebarAuditLogsRouteWithChildren =
  SidebarAuditLogsRoute._addFileChildren(SidebarAuditLogsRouteChildren)

interface SidebarEnrollmentsRouteChildren {
  SidebarEnrollmentsEnrollmentIdRoute: typeof SidebarEnrollmentsEnrollmentIdRoute
  SidebarEnrollmentsCreateRoute: typeof SidebarEnrollmentsCreateRoute
  SidebarEnrollmentsIndexRoute: typeof SidebarEnrollmentsIndexRoute
}

const SidebarEnrollmentsRouteChildren: SidebarEnrollmentsRouteChildren = {
  SidebarEnrollmentsEnrollmentIdRoute: SidebarEnrollmentsEnrollmentIdRoute,
  SidebarEnrollmentsCreateRoute: SidebarEnrollmentsCreateRoute,
  SidebarEnrollmentsIndexRoute: SidebarEnrollmentsIndexRoute,
}

const SidebarEnrollmentsRouteWithChildren =
  SidebarEnrollmentsRoute._addFileChildren(SidebarEnrollmentsRouteChildren)

interface SidebarExercisesRouteChildren {
  SidebarExercisesExerciseIdRoute: typeof SidebarExercisesExerciseIdRoute
  SidebarExercisesCreateRoute: typeof SidebarExercisesCreateRoute
  SidebarExercisesIndexRoute: typeof SidebarExercisesIndexRoute
}

const SidebarExercisesRouteChildren: SidebarExercisesRouteChildren = {
  SidebarExercisesExerciseIdRoute: SidebarExercisesExerciseIdRoute,
  SidebarExercisesCreateRoute: SidebarExercisesCreateRoute,
  SidebarExercisesIndexRoute: SidebarExercisesIndexRoute,
}

const SidebarExercisesRouteWithChildren =
  SidebarExercisesRoute._addFileChildren(SidebarExercisesRouteChildren)

interface SidebarInstructorsRouteChildren {
  SidebarInstructorsInstructorIdRoute: typeof SidebarInstructorsInstructorIdRoute
  SidebarInstructorsCreateRoute: typeof SidebarInstructorsCreateRoute
  SidebarInstructorsIndexRoute: typeof SidebarInstructorsIndexRoute
}

const SidebarInstructorsRouteChildren: SidebarInstructorsRouteChildren = {
  SidebarInstructorsInstructorIdRoute: SidebarInstructorsInstructorIdRoute,
  SidebarInstructorsCreateRoute: SidebarInstructorsCreateRoute,
  SidebarInstructorsIndexRoute: SidebarInstructorsIndexRoute,
}

const SidebarInstructorsRouteWithChildren =
  SidebarInstructorsRoute._addFileChildren(SidebarInstructorsRouteChildren)

interface SidebarPaymentsRouteChildren {
  SidebarPaymentsIndexRoute: typeof SidebarPaymentsIndexRoute
}

const SidebarPaymentsRouteChildren: SidebarPaymentsRouteChildren = {
  SidebarPaymentsIndexRoute: SidebarPaymentsIndexRoute,
}

const SidebarPaymentsRouteWithChildren = SidebarPaymentsRoute._addFileChildren(
  SidebarPaymentsRouteChildren,
)

interface SidebarPlansRouteChildren {
  SidebarPlansPlanIdRoute: typeof SidebarPlansPlanIdRoute
  SidebarPlansCreateRoute: typeof SidebarPlansCreateRoute
  SidebarPlansIndexRoute: typeof SidebarPlansIndexRoute
}

const SidebarPlansRouteChildren: SidebarPlansRouteChildren = {
  SidebarPlansPlanIdRoute: SidebarPlansPlanIdRoute,
  SidebarPlansCreateRoute: SidebarPlansCreateRoute,
  SidebarPlansIndexRoute: SidebarPlansIndexRoute,
}

const SidebarPlansRouteWithChildren = SidebarPlansRoute._addFileChildren(
  SidebarPlansRouteChildren,
)

interface SidebarStudentsRouteChildren {
  SidebarStudentsStudentIdRoute: typeof SidebarStudentsStudentIdRoute
  SidebarStudentsCreateRoute: typeof SidebarStudentsCreateRoute
  SidebarStudentsIndexRoute: typeof SidebarStudentsIndexRoute
}

const SidebarStudentsRouteChildren: SidebarStudentsRouteChildren = {
  SidebarStudentsStudentIdRoute: SidebarStudentsStudentIdRoute,
  SidebarStudentsCreateRoute: SidebarStudentsCreateRoute,
  SidebarStudentsIndexRoute: SidebarStudentsIndexRoute,
}

const SidebarStudentsRouteWithChildren = SidebarStudentsRoute._addFileChildren(
  SidebarStudentsRouteChildren,
)

interface SidebarWorkoutSheetsRouteChildren {
  SidebarWorkoutSheetsWorkoutSheetIdRoute: typeof SidebarWorkoutSheetsWorkoutSheetIdRoute
  SidebarWorkoutSheetsCreateRoute: typeof SidebarWorkoutSheetsCreateRoute
  SidebarWorkoutSheetsIndexRoute: typeof SidebarWorkoutSheetsIndexRoute
}

const SidebarWorkoutSheetsRouteChildren: SidebarWorkoutSheetsRouteChildren = {
  SidebarWorkoutSheetsWorkoutSheetIdRoute:
    SidebarWorkoutSheetsWorkoutSheetIdRoute,
  SidebarWorkoutSheetsCreateRoute: SidebarWorkoutSheetsCreateRoute,
  SidebarWorkoutSheetsIndexRoute: SidebarWorkoutSheetsIndexRoute,
}

const SidebarWorkoutSheetsRouteWithChildren =
  SidebarWorkoutSheetsRoute._addFileChildren(SidebarWorkoutSheetsRouteChildren)

interface SidebarRouteRouteChildren {
  SidebarAdminUsersRoute: typeof SidebarAdminUsersRouteWithChildren
  SidebarAuditLogsRoute: typeof SidebarAuditLogsRouteWithChildren
  SidebarDashboardRoute: typeof SidebarDashboardRoute
  SidebarEnrollmentsRoute: typeof SidebarEnrollmentsRouteWithChildren
  SidebarExercisesRoute: typeof SidebarExercisesRouteWithChildren
  SidebarInstructorsRoute: typeof SidebarInstructorsRouteWithChildren
  SidebarPaymentsRoute: typeof SidebarPaymentsRouteWithChildren
  SidebarPlansRoute: typeof SidebarPlansRouteWithChildren
  SidebarStudentsRoute: typeof SidebarStudentsRouteWithChildren
  SidebarWorkoutSheetsRoute: typeof SidebarWorkoutSheetsRouteWithChildren
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarAdminUsersRoute: SidebarAdminUsersRouteWithChildren,
  SidebarAuditLogsRoute: SidebarAuditLogsRouteWithChildren,
  SidebarDashboardRoute: SidebarDashboardRoute,
  SidebarEnrollmentsRoute: SidebarEnrollmentsRouteWithChildren,
  SidebarExercisesRoute: SidebarExercisesRouteWithChildren,
  SidebarInstructorsRoute: SidebarInstructorsRouteWithChildren,
  SidebarPaymentsRoute: SidebarPaymentsRouteWithChildren,
  SidebarPlansRoute: SidebarPlansRouteWithChildren,
  SidebarStudentsRoute: SidebarStudentsRouteWithChildren,
  SidebarWorkoutSheetsRoute: SidebarWorkoutSheetsRouteWithChildren,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
  CheckInRoute: CheckInRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
